print('Basic mathematical functions')
a = float(input('Enter the value of First number : '))
b = float(input('Enter the value of Second number : '))
add = float(a+b)
sub = float(a-b)
mul = float(a*b)
div = float(a/b)
print("Addition of First & Second number is : ",add)
print("Subtraction of First & Second number is : ",sub)
print("Multiplication of First & Second number is : ",mul)
print("Division of First & Second number is : ",div)
