# list in python
num = [10,12,15,20,23]
print(num)
num[0] = 8
print(num)
print("Slicing")
num = [10,12,15,20,23]
print(num[1])
print(num[-4])
print(num[1:4])
print(num[2:])
print(num[:3])
print("-------------")
var = ["abi",36,True,5.75]
print(var)
print(type(var))
print(var[0],"Data type is : ",type(var[0]))
print(var[1],"Data type is : ",type(var[1]))
print(var[2],"Data type is : ",type(var[2]))
print(var[3],"Data type is : ",type(var[3]))
print("-------------------")
num1 =[1,2,3,4,5]
print(num1)
num1.clear()
print(num1)
num2 = [6,7,8,9,10]
num3 = num2.copy()
print(num3)
print("Count of a variable : ",num3.count(6))
print("Index of a value : ",num3.index(8))
print("Length of the list : ",len(num3))
print("maximum : ",max(num3))
print("minimum : ",min(num3))
print(num3)
print("Remove using index : ",num3.pop(2),num3)
print("Remove value : ",num3.remove(9),num3)
print("---------------")
str = ["Abi", "Kavi"]
print(str)
str.append("Deva")
print(str)
str2 = ["Suresh", "Dinesh"]
print(str2)
str.extend(str2)
print(str)
str2.insert(4,"Akash")
print(str2)
print("---------------")
ran = (list(range(5)))
print(ran)
ran1 = (list("abitutorial"))
print(ran1)
num = [65,45,62,55,42]
num.sort()
print("Sorted list : ",num)
num.sort(reverse=True)
print("Reverse Sort : ",num)
str = ["Kavi","Deva","Abi","Suresh","Dinesh"]
print(str)
str.sort()
print("Sorted list : ",str)
str.sort(reverse=True)
print("Reverse List : ",str)
str.sort(key=len)
print(str)